import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Kaiya',
      email: 'kaiya@kaiken.com',
      //password: '123456',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Mato',
      email: 'mato@kaiken.com',
      password: bcrypt.hashSync('123456'),
      //password: '654321',
      isAdmin: false,
    },
    {
      name: 'Anna',
      email: 'anna@kaiken.com',
      password: bcrypt.hashSync('anko'),
      isAdmin: true,
    },
  ],
  products: [
    {
      //_id: '1',
      name: '100 continue',
      number: '100',
      description: 'continue',
      slug: '100-continue',
      category: '100',
      image: '/images/100.png',
      price: 100,
      countInStock: 10,
      breed: 'Kaiken',
      rating: 5,
    },
    {
      //_id: '2',
      name: '200 ok',
      number: '200',
      description: 'ok',
      slug: '200-ok',
      category: '200',
      image: '/images/200.png',
      price: 100,
      countInStock: 5,
      breed: 'Kaiken',
      rating: 4,
    },
    {
      //_id: '3',
      name: '302 found',
      number: '302',
      description: 'found',
      slug: '302-found',
      category: '300',
      image: '/images/302.png',
      price: 110,
      countInStock: 2,
      breed: 'Kaiken',
      rating: 4.5,
    },
    {
      //_id: '4',
      name: '404 not found',
      number: '404',
      description: 'not found',
      slug: '404-not-found',
      category: '400',
      image: '/images/404.png',
      price: 150,
      countInStock: 0,
      breed: 'Kaiken',
      rating: 4.8,
    },
    {
      //_id: '5',
      name: '525 SSL handshake fail',
      number: '525',
      description: 'handshake fail',
      slug: '525-ssl-handshake-fail',
      category: '500',
      image: '/images/525.png',
      price: 150,
      countInStock: 17,
      breed: 'Kaiken',
      rating: 4.8,
    },
    {
      //_id: '6',
      name: '498 token expired/invalid',
      number: '498',
      description: 'token expired/invalid',
      slug: '498-token-expired-invalid',
      category: '400',
      image: '/images/498.png',
      price: 130,
      countInStock: 8,
      breed: 'Kaiken',
      rating: 4.8,
    },
    {
      //_id: '7',
      name: '425 too early',
      number: '425',
      description: 'too early',
      slug: '425-too-early',
      category: '400',
      image: '/images/425.png',
      price: 150,
      countInStock: 0,
      breed: 'Kaiken',
      rating: 4.8,
    },
    {
      //_id: '8',
      name: '420 enhance your calm',
      number: '420',
      description: 'enhance your calm',
      slug: '420-enhance-your-calm',
      category: '400',
      image: '/images/420.png',
      price: 150,
      countInStock: 3,
      breed: 'Kaiken',
      rating: 4.8,
    },
    {
      //_id: '9',
      name: '416 request range not satisfiable',
      number: '416',
      description: 'request range not staisfiable',
      slug: '416-request-range-not-satisfiable',
      category: '400',
      image: '/images/416.png',
      price: 150,
      countInStock: 23,
      breed: 'Kaiken',
      rating: 4.8,
    },
    {
      //_id: '10',
      name: '411 length required',
      number: '411',
      description: 'length required',
      slug: '400-length-required',
      category: '400',
      image: '/images/411_02.png',
      price: 150,
      countInStock: 66,
      breed: 'Kaiken',
      rating: 4.8,
    },
    {
      //_id: '11',
      name: '206 partial content',
      number: '206',
      description: 'partial content',
      slug: '206-partial-content',
      category: '200',
      image: '/images/206.png',
      price: 150,
      countInStock: 11,
      breed: 'Kaiken',
      rating: 4.8,
    },
    {
      //_id: '12',
      name: '207 multi-status',
      number: '207',
      description: 'multi-status',
      slug: '207-multi-status',
      category: '200',
      image: '/images/207.png',
      price: 150,
      countInStock: 31,
      breed: 'Kaiken',
      rating: 4.8,
    },
    {
      //_id: '13',
      name: '304 not modified',
      number: '304',
      description: 'not modified',
      slug: '304-not-modified',
      category: '300',
      image: '/images/304.png',
      price: 150,
      countInStock: 37,
      breed: 'Kaiken',
      rating: 4.8,
    },
    {
      // _id: '14',
      name: '401 unauthorized',
      number: '401',
      description: 'unauthorized',
      slug: '401-unauthorized',
      category: '400',
      image: '/images/401.png',
      price: 150,
      countInStock: 25,
      breed: 'Kaiken',
      rating: 4.8,
    },
    {
      //_id: '15',
      name: '407 proxy authentication required',
      number: '407',
      description: 'proxy authentication required',
      slug: '407-proxy-authentication-required',
      category: '400',
      image: '/images/407.png',
      price: 150,
      countInStock: 35,
      breed: 'Kaiken',
      rating: 4.8,
    },
    {
      //_id: '16',
      name: '402 payment required',
      number: '402',
      description: 'payment required',
      slug: '402-payment-required',
      category: '400',
      image: '/images/402.png',
      price: 150,
      countInStock: 20,
      breed: 'Kaiken',
      rating: 4.8,
    },
  ],
};

export default data;
